"""
main.py
-------
Task 2: FastAPI Wrapper for the Semantic Matching Engine

Exposes three endpoints:
  POST /match          — receives extraction engine JSON, returns matched activity
  POST /reload-index   — reloads Primavera Excel without restarting the server
  GET  /health         — returns index load status and activity count

The matching logic lives entirely in match_engine.py.
This file is the HTTP layer only — it validates inputs, calls the engine,
and formats responses. It contains no matching logic itself.

Author: SIH 2026 — Fuzzy Matching & System Integration Team

To run:
  uvicorn main:app --reload --port 8000

Interactive API docs (auto-generated by FastAPI):
  http://127.0.0.1:8000/docs
"""

import os
from contextlib import asynccontextmanager
from typing import Optional

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

# Import our matching engine module.
# All in-memory state (model, activity_index, embeddings) lives there.
import match_engine


# ---------------------------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------------------------

# Default path to the Primavera Excel file, relative to where the server runs.
# Change this if the file is stored elsewhere.
DEFAULT_INDEX_PATH = "primavera_schedule.xlsx"


# ---------------------------------------------------------------------------
# PYDANTIC INPUT/OUTPUT MODELS
# ---------------------------------------------------------------------------
# Pydantic models serve two purposes:
#   1. Automatic input validation — FastAPI returns a 422 error if the
#      incoming JSON doesn't match the schema, before our code even runs.
#   2. Documentation — FastAPI auto-generates /docs from these models.


class ActivityLogInput(BaseModel):
    """
    Input received FROM Member 5's extraction engine.
    This is the locked data contract — field names and types must not change.

    Example:
        {
          "activity_description": "column footing concrete pouring Unit 7",
          "discipline": "Civil",
          "actual_start": "2026-09-01T06:00",
          "actual_end": null,
          "location": "Unit 7, Grid C-7/F-12",
          "reported_by": "Rajan",
          "source_format": "free_text"
        }
    """
    # The only field we actually use for matching — required, cannot be empty.
    activity_description: str = Field(
        ...,
        min_length=1,
        description="Natural language description of the site activity.",
        examples=["column footing concrete pouring Unit 7"],
    )

    # Used for discipline pre-filtering. Optional — if null, full index is searched.
    discipline: Optional[str] = Field(
        None,
        description="Civil | Piping | Electrical | Instrumentation | HSE. "
                    "If provided, matching is restricted to this discipline only.",
    )

    # The fields below are passed through from the extraction engine.
    # We store them as-is and forward them to the database. We do not use
    # them in matching logic — they are for traceability.
    actual_start:   Optional[str] = Field(None, description="ISO datetime e.g. 2026-09-01T06:00")
    actual_end:     Optional[str] = Field(None)
    location:       Optional[str] = Field(None)
    reported_by:    Optional[str] = Field(None)
    source_format:  Optional[str] = Field(None, description="free_text or voice")


class MatchResult(BaseModel):
    """
    Output sent TO the database/backend.
    This is the locked data contract — field names and types must not change.

    Example:
        {
          "matched_activity_id": "L5-CIVIL-2847",
          "matched_activity_name": "Concrete placement column foundations Unit 7",
          "confidence_score": 91.4,
          "match_status": "auto_linked",
          "rejection_reason": null
        }
    """
    matched_activity_id:   str
    matched_activity_name: str
    confidence_score:      float   # 0.0 – 100.0, rounded to 2 decimal places
    match_status:          str     # "auto_linked" | "review_queue" | "unplanned"

    # rejection_reason is null when match_status is "auto_linked".
    # It contains a human-readable explanation for "review_queue" and "unplanned".
    # This is an additive field — it does not break the core 4-field contract.
    rejection_reason: Optional[str] = None


class ReloadIndexRequest(BaseModel):
    """
    Request body for POST /reload-index.
    Accepts the path to a new Primavera Excel file.
    If not provided, re-reads the default file at its original path.
    """
    filepath: str = Field(
        DEFAULT_INDEX_PATH,
        description="Absolute or relative path to the Primavera Excel file to load.",
        examples=["primavera_schedule.xlsx", "C:/schedules/updated_schedule.xlsx"],
    )


class HealthResponse(BaseModel):
    """
    Response body for GET /health.
    Lets the caller confirm the server is running and the index is ready.
    """
    status:         str   # Always "ok" if the server is reachable
    index_loaded:   bool  # True if activity_index has been populated
    activity_count: int   # Number of activities currently in memory
    model_name:     str   # Which sentence-transformer model is loaded


class ReloadResult(BaseModel):
    """
    Response body for POST /reload-index.
    """
    status:         str
    message:        str
    activity_count: int


# ---------------------------------------------------------------------------
# APPLICATION LIFESPAN (startup / shutdown hooks)
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Runs once when the FastAPI server starts, before it accepts any requests.

    We load the Primavera activity index here — this is the "encode ONCE"
    requirement from the spec. The model and embeddings live in match_engine's
    module-level memory and are shared across all incoming requests.

    If the Excel file is missing at startup, the server still starts — it just
    returns a 503 on /match until /reload-index is called with a valid file.
    This is intentional: it lets the server boot even during early demo setup.
    """
    print("[main] Server starting — loading activity index...")
    try:
        match_engine.load_activity_index(DEFAULT_INDEX_PATH)
        print(f"[main] Startup complete. {len(match_engine.activity_index)} activities in memory.")
    except FileNotFoundError:
        # Non-fatal: server starts, but /match will return 503 until index is loaded.
        print(
            f"[main] WARNING: '{DEFAULT_INDEX_PATH}' not found at startup. "
            f"Server will start, but POST /match will return 503 until "
            f"POST /reload-index is called with a valid file."
        )
    except Exception as e:
        print(f"[main] WARNING: Could not load index at startup: {e}")

    # yield hands control to FastAPI — the server runs until it is stopped.
    yield

    # Everything after yield runs on shutdown. Nothing to clean up in our case
    # since we only use in-memory state (no open file handles or DB connections).
    print("[main] Server shutting down.")


# ---------------------------------------------------------------------------
# FASTAPI APP INSTANCE
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Intelligent Data Capture — Matching Engine API",
    description=(
        "Semantic matching engine for Primavera P6 schedule activities. "
        "Built for SIH 2026 — Infrastructure Project Management Tool.\n\n"
        "**How it works:**\n"
        "1. Upload a Primavera schedule Excel via `POST /reload-index`\n"
        "2. Send extracted activity logs from the site via `POST /match`\n"
        "3. Receive matched Primavera activity IDs with confidence scores\n"
    ),
    version="1.0.0",
    lifespan=lifespan,
)


# ---------------------------------------------------------------------------
# ENDPOINTS
# ---------------------------------------------------------------------------

@app.get(
    "/health",
    response_model=HealthResponse,
    summary="Server health check",
    tags=["System"],
)
def health_check():
    """
    Returns whether the server is running and whether the activity index
    has been loaded into memory.

    Call this first to confirm the server is ready before sending /match requests.
    """
    # Check both conditions: the list must be non-empty AND embeddings must exist.
    # Both being truthy means load_activity_index() ran successfully.
    index_loaded = (
        len(match_engine.activity_index) > 0
        and match_engine.activity_embeddings is not None
    )

    return HealthResponse(
        status="ok",
        index_loaded=index_loaded,
        activity_count=len(match_engine.activity_index),
        model_name=match_engine.MODEL_NAME,
    )


@app.post(
    "/match",
    response_model=MatchResult,
    summary="Match a site activity log to the Primavera schedule",
    tags=["Matching"],
)
def match(payload: ActivityLogInput):
    """
    Receives structured data extracted from a site worker's activity log and
    returns the closest matching activity from the Primavera schedule.

    **Discipline pre-filtering:**
    - If `discipline` is provided, only activities in that discipline are searched.
    - If `discipline` is null, the full schedule index is searched.

    **Match status thresholds:**
    - `auto_linked`  → confidence ≥ 75% (linked automatically)
    - `review_queue` → 40% ≤ confidence < 75% (flagged for manager review)
    - `unplanned`    → confidence < 40% (activity not in schedule)
    """
    # Guard: return 503 if the index was never loaded (e.g. Excel missing at startup)
    if not match_engine.activity_index:
        raise HTTPException(
            status_code=503,
            detail=(
                "Activity index is not loaded. "
                "Call POST /reload-index with a valid Primavera Excel file first."
            ),
        )

    try:
        result = match_engine.match_activity(
            extracted_description=payload.activity_description,
            discipline=payload.discipline,
        )
    except ValueError as e:
        # match_engine raises ValueError for empty descriptions.
        # FastAPI's Pydantic validation (min_length=1) should catch this first,
        # but this is a second defensive layer.
        raise HTTPException(status_code=422, detail=str(e))
    except RuntimeError as e:
        # Raised if match_engine's internal state is inconsistent.
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        # Unexpected error — return 500 with the message for debugging.
        raise HTTPException(status_code=500, detail=f"Matching engine error: {str(e)}")

    # Unpack the dict from match_engine into the Pydantic response model.
    # Pydantic validates the output types automatically before sending the response.
    return MatchResult(**result)


@app.post(
    "/reload-index",
    response_model=ReloadResult,
    summary="Reload the Primavera schedule from a new Excel file",
    tags=["System"],
)
def reload_index(request: ReloadIndexRequest):
    """
    Replaces the in-memory activity index with data from a new Primavera Excel file.
    The server does NOT need to be restarted.

    **When to call this:**
    - When the project team uploads an updated Primavera schedule
    - When the index becomes stale and needs refreshing

    **What happens:**
    - The existing in-memory embeddings are discarded
    - The new Excel is read, all activity names are re-encoded
    - Future /match requests immediately use the new index

    **This operation takes a few seconds** (re-encoding 100+ activities).
    The server remains available during the reload but may briefly return
    stale results if a /match request arrives mid-reload.
    """
    # Validate the file exists before attempting to load it.
    # os.path.exists works with both absolute and relative paths.
    if not os.path.exists(request.filepath):
        raise HTTPException(
            status_code=404,
            detail=f"Excel file not found at path: '{request.filepath}'. "
                   f"Check the filepath and try again.",
        )

    try:
        match_engine.load_activity_index(request.filepath)
    except ValueError as e:
        # Raised when required columns are missing or index is empty after load.
        raise HTTPException(status_code=422, detail=str(e))
    except Exception as e:
        # Catch-all for unexpected Excel parsing errors.
        raise HTTPException(status_code=500, detail=f"Failed to reload index: {str(e)}")

    activity_count = len(match_engine.activity_index)

    return ReloadResult(
        status="success",
        message=f"Activity index reloaded successfully from '{request.filepath}'.",
        activity_count=activity_count,
    )
